apiVersion: v1                                                                                                                                          
kind: PersistentVolume                                                                                                                                  
metadata:                                                                                                                                               
  name: transmission-pv
  labels:                                                                                                                                               
    app: transmission                                                                                                                                         
spec:                                                                                                                                                   
  storageClassName: manual                                                                                                                              
  capacity:                                                                                                                                             
    storage: 500Gi                                                                                                                                      
  accessModes:                                                                                                                                          
    - ReadWriteMany                                                                                                                                     
  nfs:                                                                                                                                                  
    path: /zfs/transmission
    server: node05
